services:
  frontend:
    build: .
    image: clientes-react
    container_name: clientes-react
    restart: always
    environment:
      VIRTUAL_HOST: clientes-react.docker.sulbaranjc.com
      VIRTUAL_PORT: 80
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
